namespace Garethp.ModsOfMistriaInstallerLib.Seam;

// The generated mmapi_ext.gml, recording which symbol owns which ordinal per point.
// Live registrants only, since a vacancy's mod is not installed. Struct-key
// existence uses the [$ ] accessor and an undefined compare, because
// variable_struct_exists does not exist in this engine's GML.
public static class ExtensionRegistryRenderer
{
    public const string RegistryRel = "assets/gml/scripts/mmapi/mmapi_ext.gml";

    public static string Render(IReadOnlyList<ExtensionRegistryEntry> entries,
        IReadOnlyList<ExtensionRegistryEntry>? vacants = null)
    {
        vacants ??= [];
        List<string> lines =
        [
            "//",
            "// mmapi_ext.gml -- GENERATED BY MOMI, DO NOT EDIT.",
            "// Every live extension registrant: which symbol holds which ordinal, per",
            "// point (flat point, symbol, ordinal triples, sorted). Ledger vacancies are",
            "// absent by design - their enum member survives, their mod does not.",
            "//",
            "",
            "function mmapi_ext_catalog() {",
            "    return [",
        ];
        lines.AddRange(entries
            .OrderBy(e => e.PointId, StringComparer.Ordinal)
            .ThenBy(e => e.Ordinal)
            .Select(e => $"        \"{e.PointId}\", \"{e.Symbol}\", {e.Ordinal},"));
        lines.AddRange(
        [
            "    ];",
            "}",
            "",
            "global.__mmapi_ext_id = {};",
            "global.__mmapi_ext_symbol = {};",
            "global.__mmapi_ext_ids = {};",
            "var __mmapi_ex_list = mmapi_ext_catalog();",
            "for (var __mmapi_ex_i = 0; __mmapi_ex_i < array_length(__mmapi_ex_list); __mmapi_ex_i += 3) {",
            "    var __mmapi_ex_point = __mmapi_ex_list[__mmapi_ex_i];",
            "    var __mmapi_ex_sym = __mmapi_ex_list[__mmapi_ex_i + 1];",
            "    var __mmapi_ex_ord = __mmapi_ex_list[__mmapi_ex_i + 2];",
            "    if (global.__mmapi_ext_id[$ __mmapi_ex_point] == undefined) {",
            "        global.__mmapi_ext_id[$ __mmapi_ex_point] = {};",
            "        global.__mmapi_ext_symbol[$ __mmapi_ex_point] = {};",
            "        global.__mmapi_ext_ids[$ __mmapi_ex_point] = [];",
            "    }",
            "    global.__mmapi_ext_id[$ __mmapi_ex_point][$ __mmapi_ex_sym] = __mmapi_ex_ord;",
            "    global.__mmapi_ext_symbol[$ __mmapi_ex_point][$ string(__mmapi_ex_ord)] = __mmapi_ex_sym;",
            "    array_push(global.__mmapi_ext_ids[$ __mmapi_ex_point], __mmapi_ex_ord);",
            "}",
            "",
            "// symbol -> ordinal, undefined when the point or the symbol is absent",
            "function mmapi_ext_id(point, symbol) {",
            "    var __entries = global.__mmapi_ext_id[$ point];",
            "    if (__entries == undefined) { return undefined; }",
            "    return __entries[$ symbol];",
            "}",
            "",
            "// ordinal -> symbol, undefined when the point or the ordinal is absent",
            "function mmapi_ext_symbol(point, ordinal) {",
            "    var __entries = global.__mmapi_ext_symbol[$ point];",
            "    if (__entries == undefined) { return undefined; }",
            "    return __entries[$ string(ordinal)];",
            "}",
            "",
            "// every live ordinal for a point, ascending; empty for an unknown point",
            "function mmapi_ext_ids(point) {",
            "    var __entries = global.__mmapi_ext_ids[$ point];",
            "    if (__entries == undefined) { return []; }",
            "    return __entries;",
            "}",
            "",
            "// Ledger vacancies: symbols whose ordinal is alive (saves may still name",
            "// them) but whose mod is not installed. Consumed by the framework's",
            "// mmapi_ext_is_vacant(), which the npc_is_unlocked seam asks so vacants",
            "// stay out of the journal. Flat point, symbol, ordinal triples, sorted.",
            "function mmapi_ext_vacant_catalog() {",
            "    return [",
        ]);
        lines.AddRange(vacants
            .OrderBy(e => e.PointId, StringComparer.Ordinal)
            .ThenBy(e => e.Ordinal)
            .Select(e => $"        \"{e.PointId}\", \"{e.Symbol}\", {e.Ordinal},"));
        lines.AddRange(
        [
            "    ];",
            "}",
            "",
            "global.__mmapi_ext_vacant = {};",
            "var __mmapi_ev_list = mmapi_ext_vacant_catalog();",
            "for (var __mmapi_ev_i = 0; __mmapi_ev_i < array_length(__mmapi_ev_list); __mmapi_ev_i += 3) {",
            "    var __mmapi_ev_point = __mmapi_ev_list[__mmapi_ev_i];",
            "    if (global.__mmapi_ext_vacant[$ __mmapi_ev_point] == undefined) {",
            "        global.__mmapi_ext_vacant[$ __mmapi_ev_point] = {};",
            "    }",
            "    global.__mmapi_ext_vacant[$ __mmapi_ev_point][$ string(__mmapi_ev_list[__mmapi_ev_i + 2])] =",
            "        __mmapi_ev_list[__mmapi_ev_i + 1];",
            "}",
            "",
        ]);
        return string.Join("\n", lines);
    }
}

// One live registrant, as the registry sees it.
public record ExtensionRegistryEntry(string PointId, string Symbol, long Ordinal);
