namespace Garethp.ModsOfMistriaInstallerLib.Seam;

// The generated mmapi_hook_catalog.gml: every declared hook name with its
// kind, plus the alias and contention tables. Flat alternating pairs, since
// the compat dialect is not trusted with chained array indexing.
public static class HookCatalogRenderer
{
    public static string Render(SeamCatalog catalog)
    {
        var declarations = catalog.HookDeclarations
            .OrderBy(d => d.Name, StringComparer.Ordinal)
            .ToList();

        List<string> lines =
        [
            "//",
            "// mmapi_hook_catalog.gml -- GENERATED BY MOMI, DO NOT EDIT.",
            "// Every declared hook name with its kind (flat name, kind pairs, sorted),",
            "// covering seam-provided and runtime-emitted hooks alike.",
            "//",
            "",
            "function mmapi_hook_catalog() {",
            "    return [",
        ];
        lines.AddRange(declarations.Select(d => $"        \"{d.Name}\", \"{d.Kind.CatalogName()}\","));
        lines.AddRange(
        [
            "    ];",
            "}",
            "",
            "// Old hook names that still resolve (flat alias, canonical pairs).",
            "function mmapi_hook_alias_catalog() {",
            "    return [",
        ]);
        lines.AddRange(declarations.SelectMany(d => d.Aliases.Select(a => $"        \"{a}\", \"{d.Name}\",")));
        lines.AddRange(
        [
            "    ];",
            "}",
            "",
            "// Override hooks' contention class (flat name, contention pairs): whether",
            "// rival overrides coexist by claiming disjoint targets (claim-scoped) or",
            "// genuinely conflict (exclusive).",
            "function mmapi_hook_contention_catalog() {",
            "    return [",
        ]);
        lines.AddRange(declarations
            .Where(d => d.Contention is not null)
            .Select(d => $"        \"{d.Name}\", \"{d.Contention!.Value.CatalogName()}\","));
        lines.AddRange(
        [
            "    ];",
            "}",
            "",
            "// Publish the tables at file scope: hook_name -> kind, alias -> canonical,",
            "// override hook_name -> contention.",
            "// mmapi_hook_exists() and friends consult the globals instead of calling",
            "// mmapi_hook_catalog() because unresolved names are COMPILE errors under",
            "// fabricator: the framework must work when this generated file is absent",
            "// (unit tests / bare engine), so it can never reference the function by name.",
            "global.__mmapi_hook_catalog = {};",
            "var __mmapi_hc_list = mmapi_hook_catalog();",
            "for (var __mmapi_hc_i = 0; __mmapi_hc_i < array_length(__mmapi_hc_list); __mmapi_hc_i += 2) {",
            "    global.__mmapi_hook_catalog[$ __mmapi_hc_list[__mmapi_hc_i]] = __mmapi_hc_list[__mmapi_hc_i + 1];",
            "}",
            "global.__mmapi_hook_aliases = {};",
            "var __mmapi_ha_list = mmapi_hook_alias_catalog();",
            "for (var __mmapi_ha_i = 0; __mmapi_ha_i < array_length(__mmapi_ha_list); __mmapi_ha_i += 2) {",
            "    global.__mmapi_hook_aliases[$ __mmapi_ha_list[__mmapi_ha_i]] = __mmapi_ha_list[__mmapi_ha_i + 1];",
            "}",
            "global.__mmapi_hook_contention = {};",
            "var __mmapi_hn_list = mmapi_hook_contention_catalog();",
            "for (var __mmapi_hn_i = 0; __mmapi_hn_i < array_length(__mmapi_hn_list); __mmapi_hn_i += 2) {",
            "    global.__mmapi_hook_contention[$ __mmapi_hn_list[__mmapi_hn_i]] = __mmapi_hn_list[__mmapi_hn_i + 1];",
            "}",
            "",
        ]);
        return string.Join("\n", lines);
    }
}
