using System.Text.Json;
using Garethp.ModsOfMistriaInstallerLib.Collector;

namespace Garethp.ModsOfMistriaInstallerLib.Seam;

// The generated mmapi_monster_catalog.gml: built-in monster names, custom
// monster owners, and custom category descriptors for this install.
public static class MonsterRegistryRenderer
{
    public const string RegistryRel = "assets/gml/scripts/mmapi/mmapi_monster_catalog.gml";

    public static string Render(MonsterCollection monsters)
    {
        List<string> lines =
        [
            "//",
            "// mmapi_monster_catalog.gml -- GENERATED BY MOMI, DO NOT EDIT.",
            "// Built-in monster names, custom monster owners and category descriptors",
            "// for this install.",
            "//",
            "",
            "global.__mmapi_custom_monsters_enabled = true;",
            "global.__mmapi_vanilla_monster_keys = {};",
        ];
        lines.AddRange(monsters.PristineKeys
            .Select(key => $"global.__mmapi_vanilla_monster_keys[$ {JsonSerializer.Serialize(key)}] = true;"));

        lines.Add("global.__mmapi_custom_monster_owners = {};");
        lines.AddRange(monsters.Definitions
            .OrderBy(definition => definition.Key, StringComparer.Ordinal)
            .Select(definition => "global.__mmapi_custom_monster_owners[$ "
                                  + JsonSerializer.Serialize(definition.Key) + "] = "
                                  + JsonSerializer.Serialize(definition.Mod.GetId()) + ";"));
        lines.Add("global.__mmapi_monster_category_catalog = [");
        lines.AddRange(monsters.Categories
            .OrderBy(category => category.Key, StringComparer.Ordinal)
            .Select(category => "    { key: " + JsonSerializer.Serialize(category.Key)
                + ", mod_name: " + JsonSerializer.Serialize(category.Mod.GetId())
                + ", state_names: ["
                + string.Join(", ", category.States.Select(state => JsonSerializer.Serialize(state)))
                + "] },"));
        lines.AddRange(
        [
            "];",
            "",
        ]);
        return string.Join("\n", lines);
    }
}
