using Garethp.ModsOfMistriaInstallerLib.Collector;
using Garethp.ModsOfMistriaInstallerLib.ModTypes;
using Garethp.ModsOfMistriaInstallerLib.Operations;
using Garethp.ModsOfMistriaInstallerLib.Utils;
using Tomlyn.Model;

namespace Garethp.ModsOfMistriaInstallerLib.Installer;

// Installs all TOML files from a mod:
//   • spr_*.meta.toml   → copies to assets/, injects the ID from FileNameUIDMapping
//   • poly_*.meta.toml  → copies to assets/, generates a new ID, links required_assets
//   • other *.toml      → merges with the existing game file using MOMI patch semantics
//   • other *.meta.toml → copies/merges as plain TOML
//
// ImageInstaller must run first so FileNameUIDMapping is populated.
public class TOMLInstaller : Installer
{
    public TOMLInstaller(
        string fomLocation,
        InstallManifest manifest,
        Dictionary<string, string> fileNameUIDMapping)
        : base(fomLocation, manifest, fileNameUIDMapping) { }

    public override void Install(IMod mod, Action<string, string> reportStatus)
    {
        var collector = new TOMLCollector();
        collector.Collect(mod);

        foreach (var group in collector.Groups)
        {
            if (group.HasAnimation)
                InstallAnimationMeta(mod, group, reportStatus);

            if (group.HasShape)
                InstallShapeMeta(mod, group, reportStatus);
        }

        foreach (var relPath in collector.OtherTomlFiles)
            InstallGenericToml(mod, relPath, reportStatus);
    }

    // ── Animation .meta.toml ─────────────────────────────────────────────────

    private void InstallAnimationMeta(IMod mod, AnimationGroup group, Action<string, string> reportStatus)
    {
        var relPath = group.AnimationMetaRelPath!;
        var dest    = DestinationPath(relPath);

        var toml = Toml.LoadToml(Path.Combine(mod.GetBasePath(), relPath));
        var meta  = EnsureTable(toml, "meta_properties");

        // Assign the ID generated by ImageInstaller, or create one now if the
        // animation has no image strip (pure metadata-only animation).
        if (!FileNameUIDMapping.TryGetValue(group.BaseName, out var id))
        {
            id = IDManager.GenerateUniqueId();
            FileNameUIDMapping[group.BaseName] = id;
        }

        meta["id"] = id;

        Dirty(dest);
        MergeOrWriteToml(toml, dest);
        reportStatus($"Installed animation meta: {relPath}", "");
    }

    // ── Poly .meta.toml ──────────────────────────────────────────────────────

    private void InstallShapeMeta(IMod mod, AnimationGroup group, Action<string, string> reportStatus)
    {
        var relPath = group.ShapeMetaRelPath!;
        var dest    = DestinationPath(relPath);

        var toml = Toml.LoadToml(Path.Combine(mod.GetBasePath(), relPath));
        var meta  = EnsureTable(toml, "meta_properties");

        meta["id"] = IDManager.GenerateUniqueId();

        // Link to the paired animation if one exists
        if (FileNameUIDMapping.TryGetValue(group.BaseName, out var animId))
            meta["required_assets"] = new TomlArray { animId };

        Dirty(dest);
        MergeOrWriteToml(toml, dest);
        reportStatus($"Installed shape meta: {relPath}", "");
    }

    // ── Generic TOML / ungrouped .meta.toml ──────────────────────────────────

    private void InstallGenericToml(IMod mod, string relPath, Action<string, string> reportStatus)
    {
        var dest = DestinationPath(relPath);
        var src  = Path.Combine(mod.GetBasePath(), relPath);

        var sourceToml = Toml.LoadToml(src);

        Dirty(dest);
        MergeOrWriteToml(sourceToml, dest);
        reportStatus($"Installed TOML: {relPath}", "");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    // Merges sourceToml into the existing destination file (if it exists),
    // or writes it directly if the destination is new.
    private static void MergeOrWriteToml(TomlTable sourceToml, string destPath)
    {
        if (!File.Exists(destPath))
        {
            Toml.SaveToml(sourceToml, destPath);
            return;
        }

        var destToml = Toml.LoadToml(destPath);
        MOMIOperations.MergeTomlTables(destToml, sourceToml);
        Toml.SaveToml(destToml, destPath);
    }

    private static TomlTable EnsureTable(TomlTable parent, string key)
    {
        if (!parent.TryGetValue(key, out var obj) || obj is not TomlTable table)
        {
            table = new TomlTable();
            parent[key] = table;
        }
        return table;
    }
}
