using Garethp.ModsOfMistriaInstallerLib.ModTypes;
using SixLabors.ImageSharp;
using Tomlyn.Model;

namespace Garethp.ModsOfMistriaInstallerLib.Generator;

// Handles the folder-based compact furniture layout:
//
//   momi/furniture/images/objects/*.png  -> animations/Placeables/Objects/Modded Furniture/
//                                          (+ shapes/Placeables/Objects/Modded Furniture/poly_*)
//   momi/furniture/images/ui/*.png       -> animations/Item Icons/Placeables/Furniture/Modded Furniture/
//   momi/furniture/sprites/*.toml        -> optional per-sprite overrides (see below)
//   momi/furniture/items/*.toml          -> handled by FurnitureInstaller
//                                          (merged into fiddle/items/furniture/<file>.toml)
//   momi/furniture/objects/*.toml        -> handled by FurnitureInstaller
//                                          (merged into fiddle/object_prototypes/furniture.toml)
//
// The folder a PNG sits in decides where it installs and what its defaults are —
// no naming convention required.  For every PNG this produces a virtual
// spr_*.meta.toml (and poly_*.meta.toml for object sprites) at the install
// location, plus a redirect that makes the PNG itself appear alongside the
// generated meta so ImageInstaller packs it into an atlas unchanged.
//
// IDs are always generated by MOMI; dimensions is always frame_size×frame_len;
// poly required_assets links are wired automatically by TOMLInstaller.
//
// A sprites/*.toml section is only needed when the defaults don't fit
// (multi-frame animations, custom anchors or collision boxes):
//
//   [cottage_heart_picket_fence]        # sprite name — spr_ prefix optional
//   frame_size = [32, 32]               # default: the whole PNG (single frame)
//   frame_len  = 16                     # default: PNG width ÷ frame width
//   duration   = 0.1                    # default: 0.1 when animated, else 0.0
//   atlas      = "Default"              # default: "Default" (objects) / "UI" (ui)
//   offset     = { horizontal = "Middle", vertical = "Middle" }   # anchor
//   shape_offset = [-16, -16]           # default: derived from the anchor
//   shape_size   = [32, 32]             # default: frame_size
public class CompactFurnitureGenerator
{
    private const string ObjectsImageFolder = "momi/furniture/images/objects";
    private const string UiImageFolder      = "momi/furniture/images/ui";
    private const string SpritesFolder      = "momi/furniture/sprites";

    private const string ObjectsAnimTarget  = "animations/Placeables/Furniture/Modded Furniture";
    private const string ObjectsShapeTarget = "shapes/Placeables/Furniture/Modded Furniture";
    private const string UiAnimTarget       = "animations/Item Icons/Placeables/Furniture/Modded Furniture";
    private const string UiShapeTarget      = "shapes/Item Icons/Placeables/Furniture/Modded Furniture";

    // Adds generated meta files to virtualFiles and PNG relocations to redirects
    // (virtual install path -> real path inside the mod).
    public void Generate(
        IMod mod,
        Dictionary<string, string> virtualFiles,
        Dictionary<string, string> redirects)
    {
        var settings = CollectSpriteSettings(mod);

        // Recursive: modders may organise PNGs into any subfolder structure they
        // like inside images/objects and images/ui — everything is flattened
        // into the one target folder, so filenames must be unique.
        foreach (var relPath in FindPngsRecursive(mod, ObjectsImageFolder))
            GenerateObjectSprite(mod, relPath, settings, virtualFiles, redirects);

        foreach (var relPath in FindPngsRecursive(mod, UiImageFolder))
            GenerateUiSprite(mod, relPath, settings, virtualFiles, redirects);
    }

    // Enumerates all PNGs under folder (any depth) as forward-slash relative paths.
    private static IEnumerable<string> FindPngsRecursive(IMod mod, string folder)
    {
        var prefix = folder + "/";
        return mod.GetAllFiles(".png")
            .Select(p => OutfitGenerator.Relativize(mod, p))
            .Where(p => p.Replace('\\', '/').StartsWith(prefix, StringComparison.OrdinalIgnoreCase));
    }

    // Per-sprite generation

    private static void GenerateObjectSprite(
        IMod mod, string pngRelPath,
        Dictionary<string, TomlTable> settings,
        Dictionary<string, string> virtualFiles,
        Dictionary<string, string> redirects)
    {
        var stem = Path.GetFileNameWithoutExtension(pngRelPath);   // "spr_x"
        var key  = StripSprPrefix(stem);                            // "x"

        // Atlas / anchor are chosen from the sprite-name conventions (vanilla):
        //   *_shadow            -> Shadow atlas
        //   spr_ui_*            -> UI atlas (crafting previews live beside object art)
        //   everything else     -> Default atlas
        //   *_preview           -> anchored top-left
        //   other object sprites-> anchored bottom-centre (base of the furniture)
        var isUiSprite = stem.StartsWith("spr_ui_", StringComparison.OrdinalIgnoreCase);
        var isPreview  = stem.EndsWith("_preview", StringComparison.OrdinalIgnoreCase);
        var isShadow   = stem.Contains("_shadow", StringComparison.OrdinalIgnoreCase);

        var geo = ResolveGeometry(mod, pngRelPath, settings, key,
            defaultAtlas:   isShadow ? "Shadow" : isUiSprite ? "UI" : "Default",
            defaultAnchorH: isPreview ? "Left" : "Middle",
            defaultAnchorV: isPreview ? "Top"  : isUiSprite ? "Middle" : "Bottom");
        if (geo is null) return;

        // Every sprite gets a poly (vanilla ships one for every sprite, including
        // shadows, tops and previews — a missing preview poly is what triggers
        // "invalid asset id, required Shape" in the crafting menu).
        virtualFiles.TryAdd($"{ObjectsAnimTarget}/{stem}.meta.toml", AnimationMeta(geo));
        virtualFiles.TryAdd($"{ObjectsShapeTarget}/poly_{key}.meta.toml",
            ShapeMeta(geo.ShapeW, geo.ShapeH, geo.ShapeOx, geo.ShapeOy));
        redirects.TryAdd($"{ObjectsAnimTarget}/{stem}.png", pngRelPath);
    }

    private static void GenerateUiSprite(
        IMod mod, string pngRelPath,
        Dictionary<string, TomlTable> settings,
        Dictionary<string, string> virtualFiles,
        Dictionary<string, string> redirects)
    {
        var stem = Path.GetFileNameWithoutExtension(pngRelPath);
        var key  = StripSprPrefix(stem);

        var geo = ResolveGeometry(mod, pngRelPath, settings, key, defaultAtlas: "UI");
        if (geo is null) return;

        virtualFiles.TryAdd($"{UiAnimTarget}/{stem}.meta.toml", AnimationMeta(geo));
        virtualFiles.TryAdd($"{UiShapeTarget}/poly_{key}.meta.toml",
            ShapeMeta(geo.ShapeW, geo.ShapeH, geo.ShapeOx, geo.ShapeOy));
        redirects.TryAdd($"{UiAnimTarget}/{stem}.png", pngRelPath);
    }

    // Geometry resolution

    private sealed class SpriteGeometry
    {
        public int    FrameW, FrameH, FrameCount;
        public double Duration;
        public string Atlas = "Default";
        public object OffsetH = "Middle", OffsetV = "Middle";
        public int    ShapeW, ShapeH, ShapeOx, ShapeOy;
    }

    private static SpriteGeometry? ResolveGeometry(
        IMod mod, string pngRelPath,
        Dictionary<string, TomlTable> settings,
        string key, string defaultAtlas,
        string defaultAnchorH = "Middle", string defaultAnchorV = "Middle")
    {
        int pngW, pngH;
        try
        {
            using var stream = mod.ReadFileAsStream(pngRelPath);
            var info = Image.Identify(stream);
            pngW = info.Width;
            pngH = info.Height;
        }
        catch
        {
            return null;
        }

        settings.TryGetValue(key, out var s);

        // frame_size: explicit, or the whole PNG (single frame)
        int frameW = pngW, frameH = pngH;
        if (s is not null && s.TryGetValue("frame_size", out var fsObj) &&
            fsObj is TomlArray fs && fs.Count >= 2)
        {
            frameW = Convert.ToInt32(fs[0]);
            frameH = Convert.ToInt32(fs[1]);
        }

        // frame_len: explicit, or PNG width ÷ frame width when it divides evenly
        int frameCount = 1;
        if (s is not null && s.TryGetValue("frame_len", out var flObj) && flObj is not null)
            frameCount = Convert.ToInt32(flObj);
        else if (frameW > 0 && pngW % frameW == 0)
            frameCount = pngW / frameW;

        // duration: explicit, or 0.1 for animations / 0.0 for stills
        double duration = frameCount > 1 ? 0.1 : 0.0;
        if (s is not null && s.TryGetValue("duration", out var duObj) && duObj is not null)
            duration = Convert.ToDouble(duObj);

        var atlas = defaultAtlas;
        if (s is not null && s.TryGetValue("atlas", out var atObj) && atObj is string atStr &&
            !string.IsNullOrEmpty(atStr))
            atlas = atStr;

        // Anchor: default per sprite kind, or overridden via either
        //   offset = { horizontal = "Middle", vertical = "Bottom" }   (words or numbers)
        //   anchor = [x, y]                                           (numeric shorthand)
        object offsetH = defaultAnchorH, offsetV = defaultAnchorV;
        if (s is not null && s.TryGetValue("offset", out var offObj) && offObj is TomlTable off)
        {
            if (off.TryGetValue("horizontal", out var h) && h is not null) offsetH = h;
            if (off.TryGetValue("vertical",   out var v) && v is not null) offsetV = v;
        }
        if (s is not null && s.TryGetValue("anchor", out var anObj) && anObj is TomlArray an && an.Count >= 2)
        {
            offsetH = Convert.ToInt64(an[0]);
            offsetV = Convert.ToInt64(an[1]);
        }

        // Shape box: explicit, or derived from the anchor so the box covers the
        // sprite exactly (Middle → centred, Left/Top → origin at top-left, …).
        int shapeOx = AnchorToShapeOffset(offsetH, frameW);
        int shapeOy = AnchorToShapeOffset(offsetV, frameH);
        int shapeW  = frameW, shapeH = frameH;

        if (s is not null && s.TryGetValue("shape_offset", out var soObj) &&
            soObj is TomlArray so && so.Count >= 2)
        {
            shapeOx = Convert.ToInt32(so[0]);
            shapeOy = Convert.ToInt32(so[1]);
        }
        if (s is not null && s.TryGetValue("shape_size", out var ssObj) &&
            ssObj is TomlArray ss && ss.Count >= 2)
        {
            shapeW = Convert.ToInt32(ss[0]);
            shapeH = Convert.ToInt32(ss[1]);
        }

        return new SpriteGeometry
        {
            FrameW = frameW, FrameH = frameH, FrameCount = frameCount,
            Duration = duration, Atlas = atlas,
            OffsetH = offsetH, OffsetV = offsetV,
            ShapeW = shapeW, ShapeH = shapeH, ShapeOx = shapeOx, ShapeOy = shapeOy,
        };
    }

    // Middle -> -size/2, Right/Bottom -> -size, Left/Top -> 0, numeric anchor n -> -n.
    private static int AnchorToShapeOffset(object anchor, int size) => anchor switch
    {
        string a when a.Equals("Middle", StringComparison.OrdinalIgnoreCase) => -size / 2,
        string a when a.Equals("Right",  StringComparison.OrdinalIgnoreCase) ||
                      a.Equals("Bottom", StringComparison.OrdinalIgnoreCase) => -size,
        string => 0, // Left / Top / unknown words
        _ => -(int)Convert.ToDouble(anchor),
    };

    // sprites/*.toml collection

    // Returns section-name (spr_ prefix stripped) → settings table.
    // Recursive: sprites/*.toml may live in any subfolder structure.
    private static Dictionary<string, TomlTable> CollectSpriteSettings(IMod mod)
    {
        var result = new Dictionary<string, TomlTable>(StringComparer.OrdinalIgnoreCase);

        var prefix = SpritesFolder + "/";
        var files  = mod.GetAllFiles(".toml")
            .Select(p => OutfitGenerator.Relativize(mod, p))
            .Where(p => p.Replace('\\', '/').StartsWith(prefix, StringComparison.OrdinalIgnoreCase));

        foreach (var relPath in files)
        {
            var content = mod.ReadFile(relPath);
            if (string.IsNullOrWhiteSpace(content)) continue;

            TomlTable root;
            try { root = Tomlyn.TomlSerializer.Deserialize<TomlTable>(content); }
            catch { continue; }

            foreach (var (name, value) in root)
            {
                if (value is not TomlTable section) continue;
                result[StripSprPrefix(name)] = section;
            }
        }

        return result;
    }

    private static string StripSprPrefix(string name) =>
        name.StartsWith("spr_", StringComparison.OrdinalIgnoreCase) ? name[4..] : name;

    // TOML builders

    // Emits the game's minimal animation meta: frame_size + atlas are the floor,
    // and the rest are written only when they carry non-default information —
    // matching how the game itself now writes metas (frame_len/duration only for
    // animations; dimensions/filter_kind/mipmap_filter_kind/wrap are omitted and
    // defaulted by the engine).
    private static string AnimationMeta(SpriteGeometry g)
    {
        var props = new TomlTable
        {
            ["frame_size"] = new TomlArray { g.FrameW, g.FrameH },
            ["atlas"]      = g.Atlas,
        };

        if (g.FrameCount > 1)
        {
            props["frame_len"] = g.FrameCount;
            props["duration"]  = g.Duration;
        }

        // Anchor (kept for furniture/UI, which always have one).
        if (g.OffsetH is not null && g.OffsetV is not null)
            props["offset"] = new TomlTable { ["horizontal"] = g.OffsetH, ["vertical"] = g.OffsetV };

        var t = new TomlTable
        {
            ["meta_properties"]  = new TomlTable { ["asset_kind"] = "Animation" },
            ["asset_properties"] = props,
        };
        return Tomlyn.TomlSerializer.Serialize(t);
    }

    private static string ShapeMeta(int w, int h, int ox, int oy)
    {
        var t = new TomlTable
        {
            ["meta_properties"]  = new TomlTable { ["asset_kind"] = "Shape" },
            ["asset_properties"] = new TomlTable
            {
                ["kind"]       = "box",
                ["offset"]     = new TomlArray { ox, oy },
                ["dimensions"] = new TomlArray { w, h },
            }
        };
        return Tomlyn.TomlSerializer.Serialize(t);
    }
}
