//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garethp.ModsOfMistriaGUI.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Garethp.ModsOfMistriaGUI.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods Of Mistria Installer.
        /// </summary>
        public static string GUIApplicationTitle {
            get {
                return ResourceManager.GetString("GUIApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mods folder has been detected, but one can be created automatically for you..
        /// </summary>
        public static string GUICanCreateModsFolder {
            get {
                return ResourceManager.GetString("GUICanCreateModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Fields of Mistria location. Try placing this in the same folder as Fields of Mistria..
        /// </summary>
        public static string GUICouldNotFindMistria {
            get {
                return ResourceManager.GetString("GUICouldNotFindMistria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a mods folder. Try creating a folder called &apos;mods&apos; in the Fields of Mistria folder..
        /// </summary>
        public static string GUICouldNotFindMods {
            get {
                return ResourceManager.GetString("GUICouldNotFindMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All Mods.
        /// </summary>
        public static string GUIDisableAllMods {
            get {
                return ResourceManager.GetString("GUIDisableAllMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable All Mods.
        /// </summary>
        public static string GUIEnableAllMods {
            get {
                return ResourceManager.GetString("GUIEnableAllMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields of Mistria has been detected at: .
        /// </summary>
        public static string GUIFieldsOfMistriaDetectedLocation {
            get {
                return ResourceManager.GetString("GUIFieldsOfMistriaDetectedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Mods of Mistria Installer!.
        /// </summary>
        public static string GUIGreetingText {
            get {
                return ResourceManager.GetString("GUIGreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string GUIInstallButtonText {
            get {
                return ResourceManager.GetString("GUIInstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing mods....
        /// </summary>
        public static string GUIInstallInProgress {
            get {
                return ResourceManager.GetString("GUIInstallInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1}.
        /// </summary>
        public static string GUIModByAuthor {
            get {
                return ResourceManager.GetString("GUIModByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mod has errors and will not install.
        /// </summary>
        public static string GUIModHasErrors {
            get {
                return ResourceManager.GetString("GUIModHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mod has warnings that can be ignored.
        /// </summary>
        public static string GUIModHasWarnings {
            get {
                return ResourceManager.GetString("GUIModHasWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some mods require a newer version of the installer. Please update the installer..
        /// </summary>
        public static string GUIModsRequireNewerVersion {
            get {
                return ResourceManager.GetString("GUIModsRequireNewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the boxes for all the mods you want to install:.
        /// </summary>
        public static string GUIModsWillBeInstalled {
            get {
                return ResourceManager.GetString("GUIModsWillBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mods found to install.
        /// </summary>
        public static string GUINoModsToInstall {
            get {
                return ResourceManager.GetString("GUINoModsToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a location for the log file.
        /// </summary>
        public static string GUIPickLogFile {
            get {
                return ResourceManager.GetString("GUIPickLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Information.
        /// </summary>
        public static string GUIPreinstallInformationTitle {
            get {
                return ResourceManager.GetString("GUIPreinstallInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload mod list..
        /// </summary>
        public static string GUIReloadModlist {
            get {
                return ResourceManager.GetString("GUIReloadModlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log File.
        /// </summary>
        public static string GUISaveLogFile {
            get {
                return ResourceManager.GetString("GUISaveLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields Of Mistria Location:.
        /// </summary>
        public static string GUISetupMistriaLocation {
            get {
                return ResourceManager.GetString("GUISetupMistriaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods Folder:.
        /// </summary>
        public static string GUISetupModsLocation {
            get {
                return ResourceManager.GetString("GUISetupModsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall All.
        /// </summary>
        public static string GUIUninstallButtonText {
            get {
                return ResourceManager.GetString("GUIUninstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Information.
        /// </summary>
        public static string GUIUninstallInformationTitle {
            get {
                return ResourceManager.GetString("GUIUninstallInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the Mods Of Mistria Installer is available, please update.
        /// </summary>
        public static string GUIUpdateNagMessage {
            get {
                return ResourceManager.GetString("GUIUpdateNagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available.
        /// </summary>
        public static string GUIUpdateNagTitle {
            get {
                return ResourceManager.GetString("GUIUpdateNagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re running a 64-bit operating system, but have accidently downloaded the 32-bit version of MOMI. Please download the version of MOMI that does not include &quot;-x86&quot;..
        /// </summary>
        public static string GUIWarning32Bit {
            get {
                return ResourceManager.GetString("GUIWarning32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32-Bit Version Detected.
        /// </summary>
        public static string GUIWarning32BitTitle {
            get {
                return ResourceManager.GetString("GUIWarning32BitTitle", resourceCulture);
            }
        }
    }
}
