// mmapi_hooks.gml. The named-hook engine: one generic registry backing the four
// hook kinds. One hook name holds one kind; a mixed registration warns but
// still lands, since dispatchers only invoke records of their own kind.
//
//   kind     | mod-side                      | seam-side                              | semantics
//   ---------+-------------------------------+----------------------------------------+--------------------------
//   event    | mmapi_on(name, fn, opts)      | mmapi_emit(name, ctx)                  | observe-only fan-out
//   filter   | mmapi_filter(name, fn, opts)  | v = mmapi_apply_filters(name, v, ctx)  | chained value transform
//   guard    | mmapi_guard(name, fn, opts)   | if (mmapi_check_guards(name, ctx)) ... | any false return vetoes
//   override | mmapi_override(name, fn, opts)| r = mmapi_run_override(name, ctx)      | first non-undefined wins
//
// opts is an optional struct { priority, mod_name, before, after }. Priority
// defaults to 0 and lower runs first; equal priorities keep registration order.
// before/after are mod-relative edges, taking a mod name or an array of them.
// Example: { after: "example_mod" } → run mine after example_mod's handlers.
// The handler array is re-sorted on every registration, so an edge naming a mod
// that registers later still lands. Contradictory edges warn and keep the
// priority order. Dispatch never sorts.
//
// The installed catalog (mmapi_hook_catalog.gml, generated by the installer)
// maps every hook name → its kind and every alias → its canonical name.
// Registration checks all three:
//   * an unknown name warns once: a typo, or a seam that was never installed.
//   * a kind-mismatched directive warns once per hook and mod, because an
//     mmapi_on against a filter hook would otherwise never run.
//   * an alias warns once and lands on the canonical name.
// A duplicate registration (same hook, fn, kind and mod) warns rate-limited and
// does not land twice: installers rerun every frame, so a forgotten idempotency
// guard would pile up 60 handlers a second. A second mod overriding an
// already-overridden hook warns naming both mods, since only the first
// non-undefined result wins.
//
// Hot-path disciplines, since monster.step_begin runs per monster per frame:
// dispatch does one registry lookup by hook name, missing and empty hooks
// return immediately, and the engine never allocates ctx structs.
//
// Error isolation: every handler call sits in a plain try/catch at the call
// site. A failure increments the owning mod's error count, logs a rate-limited
// Warn, and the chain continues - a filter keeps the current value, a guard
// counts as allow, event and override continue to the next handler. A change
// here has to keep every one of those outcomes holding. These calls used to go
// through the zero-argument __mmapi_guarded_call trampoline, because a
// try/catch here was believed inert (the dispatchers take arguments). That was
// false - see mmapi.gml.

function mmapi_on(hook_name, handler, opts) {
    __mmapi_hook_register("event", hook_name, handler, opts);
}

function mmapi_filter(hook_name, handler, opts) {
    __mmapi_hook_register("filter", hook_name, handler, opts);
}

function mmapi_guard(hook_name, handler, opts) {
    __mmapi_hook_register("guard", hook_name, handler, opts);
}

function mmapi_override(hook_name, handler, opts) {
    __mmapi_hook_register("override", hook_name, handler, opts);
}

function __mmapi_hook_register(kind, hook_name, handler, opts) {
    if (global[$ "__mmapi_hooks"] == undefined) { global.__mmapi_hooks = {}; }
    var registry = global.__mmapi_hooks;

    var priority = 0;
    var mod_name = mmapi_current_mod();
    var before = undefined;
    var after = undefined;
    if (opts != undefined) {
        if (opts[$ "priority"] != undefined) { priority = opts.priority; }
        if (opts[$ "mod_name"] != undefined) { mod_name = opts.mod_name; }
        if (opts[$ "before"] != undefined) { before = __mmapi_hook_mod_list(opts.before); }
        if (opts[$ "after"] != undefined) { after = __mmapi_hook_mod_list(opts.after); }
    }

    hook_name = __mmapi_hook_resolve_alias(hook_name, mod_name);
    __mmapi_hook_warn_if_uncataloged(hook_name, mod_name);
    __mmapi_hook_warn_if_kind_mismatch(kind, hook_name, mod_name);

    var handlers = registry[$ hook_name];
    if (handlers == undefined) {
        handlers = [];
        registry[$ hook_name] = handlers;
    }

    // A duplicate (same fn, kind and mod) does not land twice: installers rerun
    // every frame, so an unguarded registration would compound. This check runs
    // first, so the per-frame duplicate path reaches no other warning below.
    for (var i = 0; i < array_length(handlers); i++) {
        var existing = handlers[i];
        if (existing.fn == handler && existing.mod_name == mod_name && existing.kind == kind) {
            mmapi_warn_rate_limited(
                "hook_dup:" + string(hook_name) + ":" + string(mod_name),
                mod_name,
                "mmapi hook " + string(hook_name) + ": duplicate registration from "
                + string(mod_name) + " skipped. Guard the installer with a marker");
            return;
        }
    }

    if (array_length(handlers) > 0 && handlers[0].kind != kind) {
        mmapi_warn_rate_limited(
            "hook_mixed:" + string(hook_name),
            mod_name,
            "mmapi hook " + string(hook_name) + ": registering kind `" + kind
            + "` but the hook already holds kind `" + handlers[0].kind
            + "`. One hook name should hold one kind");
    }

    if (kind == "override") {
        for (var i = 0; i < array_length(handlers); i++) {
            var rival = handlers[i];
            if (rival.kind == "override" && rival.mod_name != mod_name) {
                // Claim-scoped hooks expect rival overrides: each handler claims
                // its own targets and returns undefined for the rest. Exclusive
                // hooks genuinely conflict.
                if (__mmapi_hook_contention(hook_name) == "claim-scoped") {
                    mmapi_log_info(mod_name,
                        "mmapi hook " + string(hook_name) + ": override registered by both "
                        + string(rival.mod_name) + " and " + string(mod_name)
                        + ". Claim-scoped: they coexist when each handler returns undefined "
                        + "for targets it does not own");
                } else {
                    mmapi_log_warn(mod_name,
                        "mmapi hook " + string(hook_name) + ": override registered by both "
                        + string(rival.mod_name) + " and " + string(mod_name)
                        + ". The first non-undefined result wins");
                }
                break;
            }
        }
    }

    if (global[$ "__mmapi_hook_seq"] == undefined) { global.__mmapi_hook_seq = 0; }
    global.__mmapi_hook_seq += 1;
    array_push(handlers, {
        fn: handler,
        priority: priority,
        mod_name: mod_name,
        kind: kind,
        seq: global.__mmapi_hook_seq,
        before: before,
        after: after,
    });
    __mmapi_hook_resort(hook_name, handlers);
}

// A before/after opt (one mod name, or an array of them) → an array.
function __mmapi_hook_mod_list(value) {
    if (is_array(value)) { return value; }
    return [value];
}

function __mmapi_hook_names_mod(mod_list, mod_name) {
    if (mod_list == undefined) { return false; }
    for (var i = 0; i < array_length(mod_list); i++) {
        if (mod_list[i] == mod_name) { return true; }
    }
    return false;
}

// Re-sort one hook's handler array: priority first, stable by registration
// sequence, then the before/after mod edges layered on top topologically,
// picking the lowest (priority, seq) among the ready records so the edge-free
// order is the priority order. Runs on every registration, never at dispatch.
// An edge cycle warns and keeps the priority order.
function __mmapi_hook_resort(hook_name, handlers) {
    var count = array_length(handlers);
    if (count < 2) { return; }

    for (var i = 1; i < count; i++) {
        var record = handlers[i];
        var j = i - 1;
        while (j >= 0 && (handlers[j].priority > record.priority
                || (handlers[j].priority == record.priority && handlers[j].seq > record.seq))) {
            handlers[j + 1] = handlers[j];
            j -= 1;
        }
        handlers[j + 1] = record;
    }

    var has_edges = false;
    for (var i = 0; i < count; i++) {
        if (handlers[i].before != undefined || handlers[i].after != undefined) {
            has_edges = true;
            break;
        }
    }
    if (has_edges == false) { return; }

    // edges[i] lists the records that must run after handlers[i], and
    // indegree[i] counts the records that must run before handlers[i]
    var edges = array_create(count, undefined);
    var indegree = array_create(count, 0);
    for (var i = 0; i < count; i++) { edges[i] = []; }
    for (var i = 0; i < count; i++) {
        var record = handlers[i];
        for (var j = 0; j < count; j++) {
            if (i == j) { continue; }
            var peer = handlers[j];
            if (__mmapi_hook_names_mod(record.after, peer.mod_name)) {
                array_push(edges[j], i);
                indegree[i] += 1;
            }
            if (__mmapi_hook_names_mod(record.before, peer.mod_name)) {
                array_push(edges[i], j);
                indegree[j] += 1;
            }
        }
    }

    var order = [];
    var placed = array_create(count, false);
    repeat (count) {
        var pick = -1;
        for (var i = 0; i < count; i++) {
            if (placed[i] || indegree[i] > 0) { continue; }
            if (pick == -1 || handlers[i].priority < handlers[pick].priority
                    || (handlers[i].priority == handlers[pick].priority
                        && handlers[i].seq < handlers[pick].seq)) {
                pick = i;
            }
        }
        if (pick == -1) {
            mmapi_warn_rate_limited("hook_edges:" + string(hook_name), "mmapi",
                "mmapi hook " + string(hook_name)
                + ": contradictory before/after constraints. Keeping priority order");
            return;
        }
        placed[pick] = true;
        array_push(order, handlers[pick]);
        var out = edges[pick];
        for (var k = 0; k < array_length(out); k++) {
            indegree[out[k]] -= 1;
        }
    }
    for (var i = 0; i < count; i++) { handlers[i] = order[i]; }
}

// ── Dispatch ──────────────────────────────────────────────────────────

// Call every event handler in dispatch order. Returns undefined.
function mmapi_emit(hook_name, ctx) {
    var registry = global[$ "__mmapi_hooks"];
    if (registry == undefined) { return undefined; }
    var handlers = registry[$ hook_name];
    if (handlers == undefined) { return undefined; }
    var count = array_length(handlers);
    for (var i = 0; i < count; i++) {
        var record = handlers[i];
        if (record.kind != "event") { continue; }
        try {
            record.fn(ctx);
        } catch (err) {
            __mmapi_hook_handler_failed(hook_name, record.mod_name, err);
        }
    }
    return undefined;
}

// Chain the value through every filter handler. A handler returning undefined
// keeps the current value, and so does a handler error.
function mmapi_apply_filters(hook_name, value, ctx) {
    var registry = global[$ "__mmapi_hooks"];
    if (registry == undefined) { return value; }
    var handlers = registry[$ hook_name];
    if (handlers == undefined) { return value; }
    var current = value;
    var count = array_length(handlers);
    for (var i = 0; i < count; i++) {
        var record = handlers[i];
        if (record.kind != "filter") { continue; }
        try {
            var result = record.fn(current, ctx);
            // typeof, not `== undefined`. The original reason (an asset value's
            // `!= undefined` being unstable on a call frame, the
            // asset-neq-undefined-unstable quirk) does not reproduce: probed
            // in-engine, an asset handle is an int64 and compares to undefined
            // perfectly sanely. typeof stays anyway, on its own merit: this
            // protocol makes "did the handler decline?" a correctness-critical
            // question on every dispatch, and a type test answers exactly that,
            // where `==` answers a value question that merely usually agrees.
            // Only a genuine undefined (filter declined) is "undefined"; any
            // real value, a sprite asset included, threads through.
            if (typeof(result) == "undefined") {
                // keep current (the filter declined)
            } else {
                current = result;
            }
        } catch (err) {
            // keep current (the handler failed)
            __mmapi_hook_handler_failed(hook_name, record.mod_name, err);
        }
    }
    return current;
}

// False when any guard returned false, short-circuiting at the first veto, else
// true. Zero handlers count as allow, and a handler error counts as allow.
//
// A guard returning 0 does not veto. The veto test was once a bare
// `result == false`, which this dialect's numeric coercion also makes true for
// 0 and 0.0; a runtime test asserting the documented behaviour caught it.
function mmapi_check_guards(hook_name, ctx) {
    var registry = global[$ "__mmapi_hooks"];
    if (registry == undefined) { return true; }
    var handlers = registry[$ hook_name];
    if (handlers == undefined) { return true; }
    var count = array_length(handlers);
    for (var i = 0; i < count; i++) {
        var record = handlers[i];
        if (record.kind != "guard") { continue; }
        var result = undefined;
        try {
            result = record.fn(ctx);
        } catch (err) {
            __mmapi_hook_handler_failed(hook_name, record.mod_name, err);
            // `result` stays undefined, which falls through to "allow" below:
            // the documented fail-open contract, reached by the same path as a
            // guard that declines. A veto is never the accident of a crash.
        }
        // Only a real boolean `false` vetoes; everything else allows. The
        // `== undefined` test came first because of quirk 2 (mmapi.gml), which
        // does not reproduce: probed on the pinned VM and in-engine, this exact
        // logic with the ordering reversed still allows. The order is kept as
        // cheap defensiveness. It costs nothing and states the protocol's
        // intent: declining is not vetoing.
        if (result == undefined) {
            continue;
        }
        // The type test, not a bare `result == false`. `==` coerces numerically
        // in this dialect, so a bare test would also catch 0 and 0.0: the types
        // differ from bool (typeof(0) is int64, typeof(0.0) is number) but the
        // comparison does not care, and a guard returning a stray zero would
        // block the player silently. This hook kind's fail-open posture exists
        // to prevent exactly that.
        //
        // `typeof(false) == "bool"` is confirmed in the shipped engine, not just
        // on the pinned VM. This briefly shipped as an exclusion of int64 and
        // number instead, which fails toward vetoing - the safe bet while "bool"
        // was unverified off-VM. Verified now, so the test reads as the rule it
        // enforces and needs no numeric enumeration to stay complete.
        if (typeof(result) == "bool" && result == false) {
            return false;
        }
    }
    return true;
}

// The first non-undefined handler result in dispatch order, else undefined.
function mmapi_run_override(hook_name, ctx) {
    var registry = global[$ "__mmapi_hooks"];
    if (registry == undefined) { return undefined; }
    var handlers = registry[$ hook_name];
    if (handlers == undefined) { return undefined; }
    var count = array_length(handlers);
    for (var i = 0; i < count; i++) {
        var record = handlers[i];
        if (record.kind != "override") { continue; }
        var result = undefined;
        try {
            result = record.fn(ctx);
        } catch (err) {
            __mmapi_hook_handler_failed(hook_name, record.mod_name, err);
            // `result` stays undefined, so a failed override falls through to
            // the next one exactly as a declining override does.
        }
        if (typeof(result) == "undefined") {
            continue;
        }
        return result;
    }
    return undefined;
}

function __mmapi_hook_handler_failed(hook_name, mod_name, err) {
    if (global[$ "__mmapi_hook_errors"] == undefined) { global.__mmapi_hook_errors = {}; }
    var errors = global.__mmapi_hook_errors;
    var count = errors[$ mod_name];
    if (count == undefined) { count = 0; }
    errors[$ mod_name] = count + 1;
    mmapi_warn_rate_limited(
        "hook:" + string(hook_name) + ":" + string(mod_name),
        mod_name,
        "mmapi hook " + string(hook_name) + ": handler from " + string(mod_name)
        + " failed: " + string(err));
}

// ── Catalog and stats ─────────────────────────────────────────────────

// True or false when the installed seam catalog is known, undefined when it is
// not, e.g. unit tests or a bare engine. The catalog file
// (mmapi_hook_catalog.gml) is generated by the installer from seams.toml.
// Calling a function that may not exist is a compile error under fabricator, so
// the generated file publishes its tables at file scope as
// global.__mmapi_hook_catalog (hook_name → kind) and
// global.__mmapi_hook_aliases (alias → canonical), and the framework consults
// the globals.
function mmapi_hook_exists(hook_name) {
    var catalog = global[$ "__mmapi_hook_catalog"];
    if (catalog == undefined) { return undefined; }
    return catalog[$ hook_name] != undefined;
}

// A hook's declared kind per the installed catalog: "event", "filter", "guard"
// or "override". undefined when the catalog is absent or the hook is unknown.
function mmapi_hook_kind(hook_name) {
    var catalog = global[$ "__mmapi_hook_catalog"];
    if (catalog == undefined) { return undefined; }
    return catalog[$ hook_name];
}

// An override hook's declared contention class per the installed catalog:
// "exclusive" or "claim-scoped". undefined when the hook is unknown or the
// catalog is absent, which covers unit tests, a bare engine, and a catalog
// generated before the field existed. Callers treat undefined as exclusive,
// the warn-louder default.
function __mmapi_hook_contention(hook_name) {
    var contention = global[$ "__mmapi_hook_contention"];
    if (contention == undefined) { return undefined; }
    return contention[$ hook_name];
}

// alias → canonical hook name. The old name still works, with one warning per
// alias and mod, so a rename never breaks a mod silently.
function __mmapi_hook_resolve_alias(hook_name, mod_name) {
    var aliases = global[$ "__mmapi_hook_aliases"];
    if (aliases == undefined) { return hook_name; }
    var canonical = aliases[$ hook_name];
    if (canonical == undefined) { return hook_name; }
    if (global[$ "__mmapi_hook_alias_warned"] == undefined) { global.__mmapi_hook_alias_warned = {}; }
    var key = string(hook_name) + ":" + string(mod_name);
    if (global.__mmapi_hook_alias_warned[$ key] == undefined) {
        global.__mmapi_hook_alias_warned[$ key] = true;
        mmapi_log_warn(mod_name,
            "mmapi hook " + string(hook_name) + " is an old name for "
            + string(canonical) + ". Update the registration");
    }
    return canonical;
}

// Warn once per hook name when registering for a hook the installed catalog
// does not know about. A seam that was never installed dispatches nothing.
function __mmapi_hook_warn_if_uncataloged(hook_name, mod_name) {
    var known = mmapi_hook_exists(hook_name);
    if (known == undefined) { return; } // no catalog (unit tests / bare engine)
    if (known) { return; }
    if (global[$ "__mmapi_hook_unknown_warned"] == undefined) { global.__mmapi_hook_unknown_warned = {}; }
    if (global.__mmapi_hook_unknown_warned[$ hook_name] != undefined) { return; }
    global.__mmapi_hook_unknown_warned[$ hook_name] = true;
    mmapi_log_warn(mod_name,
        "mmapi hook " + string(hook_name)
        + ": registered for unknown hook. Seam not installed?");
}

// Warn once per hook and mod when the directive does not match the declared
// kind. Dispatchers only invoke records of their own kind, so an mmapi_on
// against a filter hook would silently never run.
function __mmapi_hook_warn_if_kind_mismatch(kind, hook_name, mod_name) {
    var declared = mmapi_hook_kind(hook_name);
    if (declared == undefined) { return; } // no catalog, or unknown (warned above)
    if (declared == kind) { return; }
    if (global[$ "__mmapi_hook_kind_warned"] == undefined) { global.__mmapi_hook_kind_warned = {}; }
    var key = string(hook_name) + ":" + string(mod_name);
    if (global.__mmapi_hook_kind_warned[$ key] != undefined) { return; }
    global.__mmapi_hook_kind_warned[$ key] = true;
    mmapi_log_warn(mod_name,
        "mmapi hook " + string(hook_name) + " is declared kind `" + string(declared)
        + "` but was registered with " + __mmapi_hook_register_fn(kind)
        + ". Use " + __mmapi_hook_register_fn(declared));
}

function __mmapi_hook_register_fn(kind) {
    switch (kind) {
        case "event":    return "mmapi_on";
        case "filter":   return "mmapi_filter";
        case "guard":    return "mmapi_guard";
        case "override": return "mmapi_override";
        default:         return "mmapi_on";
    }
}

// Introspection for one hook: its declared kind, undefined without a catalog,
// plus every registered handler in dispatch order.
function mmapi_hook_info(hook_name) {
    var info = { name: hook_name, kind: mmapi_hook_kind(hook_name), handlers: [] };
    var registry = global[$ "__mmapi_hooks"];
    if (registry == undefined) { return info; }
    var handlers = registry[$ hook_name];
    if (handlers == undefined) { return info; }
    for (var i = 0; i < array_length(handlers); i++) {
        var record = handlers[i];
        array_push(info.handlers, {
            mod_name: record.mod_name,
            kind: record.kind,
            priority: record.priority,
        });
    }
    return info;
}

// Dots in hook names cannot be addressed as their own segment in a dotted watch
// path, so the wiring table swaps them for underscores.
// Example: "spells.cost" → "spells_cost"
// The swap is not injective, so two names that collide share one list and every
// entry carries its real name in its `hook` field.
function __mmapi_hook_stats_key(hook_name) {
    var out = "";
    var len = string_length(hook_name);
    for (var i = 1; i <= len; i++) {
        var c = string_char_at(hook_name, i);
        out += (c == ".") ? "_" : c;
    }
    return out;
}

// { hooks: struct hook_name → handler_count, errors: struct mod_name → count,
//   wiring: struct underscored_hook_name → [{ hook, mod_name, kind, priority }] }
// wiring lists every handler in dispatch order, so "whose filter runs first?"
// is answerable live from a debugger watch.
function mmapi_hook_stats() {
    var hooks = {};
    var wiring = {};
    var registry = global[$ "__mmapi_hooks"];
    if (registry != undefined) {
        var names = struct_get_names(registry);
        for (var i = 0; i < array_length(names); i++) {
            var handlers = registry[$ names[i]];
            hooks[$ names[i]] = array_length(handlers);
            var key = __mmapi_hook_stats_key(names[i]);
            var listing = wiring[$ key];
            if (listing == undefined) {
                listing = [];
                wiring[$ key] = listing;
            }
            for (var j = 0; j < array_length(handlers); j++) {
                var record = handlers[j];
                array_push(listing, {
                    hook: names[i],
                    mod_name: record.mod_name,
                    kind: record.kind,
                    priority: record.priority,
                });
            }
        }
    }

    var errors = {};
    var error_counts = global[$ "__mmapi_hook_errors"];
    if (error_counts != undefined) {
        var mods = struct_get_names(error_counts);
        for (var j = 0; j < array_length(mods); j++) {
            errors[$ mods[j]] = error_counts[$ mods[j]];
        }
    }

    return { hooks: hooks, errors: errors, wiring: wiring };
}
