name: Publish To Release

on:
  push:
    tags:
      - '*'

jobs:
  compile:

    strategy:
      fail-fast: false
      matrix:
        project: [ModsOfMistriaCommandLine, ModsOfMistriaGUI]
        arch: [linux-x64, win-x64, win-x86]
        os: [windows]
        configuration: [Release]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Publish ${{ matrix.arch }} CLI
        run: dotnet publish ${{ matrix.project }} -c ${{ matrix.configuration }} -r ${{ matrix.arch }} -o Release
      - name: Upload binaries to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload v0.1.4 Release/*