name: Upload To Nexus

on:
  push:
    branches: [ nexus-upload ]
  workflow_dispatch:

jobs:
  nexus_upload:

    strategy:
      fail-fast: false
      matrix:
        project: [ModsOfMistriaGUI]
        arch: [win-x64]
        os: [windows]
        configuration: [Release]

    runs-on: ubuntu-latest
    environment: NEXUS_TOKEN

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            3.1.x
      - name: Restore Tools
        shell: bash
        run: |
          dotnet tool install -g BUTR.NexusUploader
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Build Windows
        run: dotnet publish ModsOfMistriaGUI -c Release -r win-x64 -o Release
      - name: Get Assembly Version
        run: |
          VERSION=$(dotnet msbuild -nologo -verbosity:quiet -getProperty:AssemblyVersion ModsOfMistriaGUI)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
#      - name: Build Linux
#        run: dotnet publish ModsOfMistriaGUI -c Release -r linux-x64 -o Release
#      - uses: vimtor/action-zip@v1.3
#        with:
#          files: Release/ModsOfMistriaInstaller-linux
#          dest: Release/ModsOfMistriaInstaller-linux.zip
#      - name: Build OSX
#        run: dotnet publish ModsOfMistriaGUI -c Release -r osx-x64 -o Release
#      - uses: vimtor/action-zip@v1.3
#        with:
#          files: Release/ModsOfMistriaInstaller-osx
#          dest: Release/ModsOfMistriaInstaller-osx.zip
#      - uses: actions/upload-artifact@v6
#        with:
#          name: my-artifact-windows
#          path: Release/ModsOfMistriaInstaller.exe
#      - uses: actions/upload-artifact@v6
#        with:
#          name: my-artifact-linux
#          path: Release/ModsOfMistriaInstaller-linux.zip
#      - uses: actions/upload-artifact@v6
#        with:
#          name: my-artifact-osx
#          path: Release/ModsOfMistriaInstaller-osx.zip
      - name: Upload to NexusMods
        uses: Nexus-Mods/upload-action@v1.0.0-beta.3
        with:
          api_key: ${{ secrets.NEXUS_TOKEN }}
          file_group_id: 7261307
          filename: Release/ModsOfMistriaInstaller.exe
          version: ${{ env.APP_VERSION }}
#      - name: Run Nexus uploader
#        shell: bash
#        run: |
#          ls Release
#          unex upload 78 ./Release/ModsOfMistriaInstaller-cli.exe --game fieldsofmistria --file-name "Mods Of Mistria Installer Windows Command Line" -v ${{ steps.vars.outputs.tag }} --no-version-update 
#        env:
#          UNEX_APIKEY: ${{ secrets.NEXUS_TOKEN }}
#          UNEX_COOKIES: ${{ secrets.NEXUS_COOKIES }}
#          UNEX_DEBUG: true
