name: Upload To Nexus

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  nexus_upload:

    strategy:
      fail-fast: false
      matrix:
        project: [ModsOfMistriaGUI]
        arch: [win-x64]
        os: [windows]
        configuration: [Release]

    runs-on: ubuntu-latest
    environment: NEXUS_TOKEN

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test

      - name: Get Assembly Version
        run: |
          VERSION=$(dotnet msbuild -nologo -verbosity:quiet -getProperty:AssemblyVersion ModsOfMistriaGUI)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
        
      - name: Compile Windows
        run: dotnet publish ModsOfMistriaGUI -c Release -r win-x64 -o Release
          
      - name: Compile Linux
        run: dotnet publish ModsOfMistriaGUI -c Release -r linux-x64 -o Release
      - name: Zip Linux
        uses: vimtor/action-zip@v1.3
        with:
          files: Release/ModsOfMistriaInstaller-linux
          dest: Release/ModsOfMistriaInstaller-linux.zip
          
      - name: Compile OSX
        run: dotnet publish ModsOfMistriaGUI -c Release -r osx-x64 -o Release
      - name: Zip OSX
        uses: vimtor/action-zip@v1.3
        with:
          files: Release/ModsOfMistriaInstaller-osx
          dest: Release/ModsOfMistriaInstaller-osx.zip
          
      - name: Upload to Windows GUI NexusMods
        uses: Nexus-Mods/upload-action@v1.0.0-beta.3
        with:
          api_key: ${{ secrets.NEXUS_TOKEN }}
          file_group_id: 569647
          filename: Release/ModsOfMistriaInstaller.exe
          version: ${{ env.APP_VERSION }}
          display_name: "Mods Of Mistria Installer"
          description: "If you're on Windows, you should probably use this release"
          
      - name: Upload to Linux GUI NexusMods
        uses: Nexus-Mods/upload-action@v1.0.0-beta.3
        with:
          api_key: ${{ secrets.NEXUS_TOKEN }}
          file_group_id: 569653
          filename: Release/ModsOfMistriaInstaller-linux.zip
          version: ${{ env.APP_VERSION }}
          display_name: "Mods Of Mistria Installer Linux"
          description: "If you're on a Steam Deck, you should probably use this release"

      - name: Upload to OSX GUI NexusMods
        uses: Nexus-Mods/upload-action@v1.0.0-beta.3
        with:
          api_key: ${{ secrets.NEXUS_TOKEN }}
          file_group_id: 569668
          filename: Release/ModsOfMistriaInstaller-osx.zip
          version: ${{ env.APP_VERSION }}
          display_name: "Mods Of Mistria Installer OSX"
          description: "If you're on a Mac, you should probably use this release"